/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import { useController } from '@react-three/xr'
import { useFrame } from '@react-three/fiber'
import { Vector3 } from 'three'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mallet.gltf')
  const malletAPI = useRef(null)
  const controller = useController(props.hand)

  useFrame(()=>{
    if (controller) {
      malletAPI.current.setNextKinematicTranslation({
        x: controller.grip.position.x,
        y: controller.grip.position.y,
        z: controller.grip.position.z
      })  ;
      malletAPI.current.setNextKinematicRotation({
        x: controller.grip.rotation.x,
        y: controller.grip.rotation.y,
        z: controller.grip.rotation.z
      }) 
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <RigidBody 
        type="kinematicPosition" 
        colliders="hull" 
        ref={malletAPI}
        ccd={true}
      >
        <mesh geometry={nodes.xylophone4.geometry} material={materials.xylophone} castShadow />
      </RigidBody>
    </group>
  )
}

useGLTF.preload('/mallet.gltf')
