/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/mallet.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh geometry={nodes.xylophone4.geometry} material={materials.xylophone} />
      </RigidBody>
    </group>
  )
}

useGLTF.preload('/mallet.gltf')
