/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import { useSound } from 'use-sound'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/xylophone.gltf')
  const [playC] = useSound('/C.mp3')
  const [playD] = useSound('/D.mp3')
  const [playE] = useSound('/E.mp3')
  const [playF] = useSound('/F.mp3')
  const [playG] = useSound('/G.mp3')
  const [playA] = useSound('/A.mp3')
  const [playB] = useSound('/B.mp3')
  const [playC2] = useSound('/C2.mp3')

  return (
    <group ref={group} {...props} dispose={null}>
      <RigidBody 
        type="fixed" 
        colliders="hull"
      >
        <mesh geometry={nodes.frame.geometry} material={materials.Material} />
      </RigidBody>
      <RigidBody
        colliders="cuboid"
        enabledTranslations={[false, true, false]}
        enabledRotations={[false, false, false]}
        onCollisionEnter={({manifold}) => {
          playC()
        }}
      >
        <mesh onClick={playC} geometry={nodes.C.geometry} material={materials['Material.002']} />
      </RigidBody>
      <RigidBody
        colliders="cuboid"
        enabledTranslations={[false, true, false]}
        enabledRotations={[false, false, false]}
        onCollisionEnter={({manifold}) => {
          playD()
        }}
      >
        <mesh onClick={playD} geometry={nodes.D.geometry} material={materials['Material.003']} />
      </RigidBody>
      <RigidBody
        colliders="cuboid"
        enabledTranslations={[false, true, false]}
        enabledRotations={[false, false, false]}
        onCollisionEnter={({manifold}) => {
          playE()
        }}
      >
        <mesh onClick={playE} geometry={nodes.E.geometry} material={materials['Material.004']} />
      </RigidBody>
      <RigidBody
        colliders="cuboid"
        enabledTranslations={[false, true, false]}
        enabledRotations={[false, false, false]}
        onCollisionEnter={({manifold}) => {
          playF()
        }}
      >
        <mesh onClick={playF} geometry={nodes.F.geometry} material={materials['Material.005']} />
      </RigidBody>
      <RigidBody
        colliders="cuboid"
        enabledTranslations={[false, true, false]}
        enabledRotations={[false, false, false]}
        onCollisionEnter={({manifold}) => {
          playG()
        }}
      >
        <mesh onClick={playG} geometry={nodes.G.geometry} material={materials['Material.006']} />
      </RigidBody>
      <RigidBody
        colliders="cuboid"
        enabledTranslations={[false, true, false]}
        enabledRotations={[false, false, false]}
        onCollisionEnter={({manifold}) => {
          playA()
        }}
      >
        <mesh onClick={playA} geometry={nodes.A.geometry} material={materials['Material.007']} />
      </RigidBody>
      <RigidBody
        colliders="cuboid"
        enabledTranslations={[false, true, false]}
        enabledRotations={[false, false, false]}
        onCollisionEnter={({manifold}) => {
          playB()
        }}
      >
        <mesh onClick={playB} geometry={nodes.B.geometry} material={materials['Material.008']} />
      </RigidBody>
      <RigidBody
        enabledTranslations={[false, true, false]}
        enabledRotations={[false, false, false]}
        colliders="cuboid"
        onCollisionEnter={({manifold}) => {
          playC2()
        }}
      >
        <mesh onClick={playC2} geometry={nodes.C2.geometry} material={materials['Material.001']} />
      </RigidBody>
      <mesh geometry={nodes.Sphere.geometry} material={materials.buttons} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials.buttons} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials.buttons} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials.buttons} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials.buttons} />
      <mesh geometry={nodes.Sphere005.geometry} material={materials.buttons} />
      <mesh geometry={nodes.Sphere006.geometry} material={materials.buttons} />
      <mesh geometry={nodes.Sphere007.geometry} material={materials.buttons} />
    </group>
  )
}

useGLTF.preload('/xylophone.gltf')
