/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'
import { useSound } from 'use-sound'

const MusicalMesh = ({ onInteract, geometry, material }) => {
  return(<RigidBody
    colliders="cuboid"
    enabledTranslations={[false, true, false]}
    enabledRotations={[false, false, false]}
    onCollisionEnter={({manifold}) => {
      onInteract()
    }}
  >
    <mesh onClick={()=> onInteract()} geometry={geometry} material={material} castShadow />
  </RigidBody>

  )
}

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/xylophone.gltf')
  const [playC] = useSound('/C.mp3')
  const [playD] = useSound('/D.mp3')
  const [playE] = useSound('/E.mp3')
  const [playF] = useSound('/F.mp3')
  const [playG] = useSound('/G.mp3')
  const [playA] = useSound('/A.mp3')
  const [playB] = useSound('/B.mp3')
  const [playC2] = useSound('/C2.mp3')

  return (
    <group ref={group} {...props} dispose={null}>
      <RigidBody type='fixed'>

        <mesh geometry={nodes.frame.geometry} material={materials.Material} castShadow />
      </RigidBody>
      <MusicalMesh
        onInteract={playC} 
        geometry={nodes.C.geometry} 
        material={materials['Material.002']} />
      <MusicalMesh
        onInteract={playD} 
        geometry={nodes.D.geometry} 
        material={materials['Material.003']} />
      <MusicalMesh
        onInteract={playE} 
        geometry={nodes.E.geometry} 
        material={materials['Material.004']} />
      <MusicalMesh
        onInteract={playF} 
        geometry={nodes.F.geometry} 
        material={materials['Material.005']} />
      <MusicalMesh
        onInteract={playG} 
        geometry={nodes.G.geometry} 
        material={materials['Material.006']} />
      <MusicalMesh
        onInteract={playA} 
        geometry={nodes.A.geometry} 
        material={materials['Material.007']} />
      <MusicalMesh
        onInteract={playB} 
        geometry={nodes.B.geometry} 
        material={materials['Material.008']} />
      <MusicalMesh
        onInteract={playC2} 
        geometry={nodes.C2.geometry}
         material={materials['Material.001']} />
      <mesh geometry={nodes.Sphere.geometry} material={materials.buttons} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials.buttons} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials.buttons} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials.buttons} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials.buttons} />
      <mesh geometry={nodes.Sphere005.geometry} material={materials.buttons} />
      <mesh geometry={nodes.Sphere006.geometry} material={materials.buttons} />
      <mesh geometry={nodes.Sphere007.geometry} material={materials.buttons} />
    </group>
  )
  
}

useGLTF.preload('/xylophone.gltf')
